function macros() {
#macro DEPTH_ITEM 10
#macro DEPTH_GUI -20
#macro DEPTH_TILE -10
#macro FIELD_HALF_Y_SIZE FIELD_HEIGHT*CELL_SIZE/2
#macro FIELD_HALF_X_SIZE FIELD_WIDTH*CELL_SIZE/2
#macro FIELD_CENTERY 457
#macro FIELD_CENTERX 320
#macro CELLS_FROM_HERO 3
#macro FIELD_WIDTH 6
#macro FIELD_HEIGHT 7
#macro FIRST_CELL_X 20
#macro FIRST_CELL_Y 107
#macro CELL_SIZE_DEF 100
#macro CELL_SIZE 100
#macro Y_SIZE_DEF 1136
#macro X_SIZE_DEF 640



}
